# Form implementation generated from reading ui file '.\\templates\\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(400, 300)
        dlgAbout.setMinimumSize(QtCore.QSize(400, 300))
        dlgAbout.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setModal(True)
        self.btnCerrarAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCerrarAbout.setGeometry(QtCore.QRect(290, 260, 75, 24))
        self.btnCerrarAbout.setMinimumSize(QtCore.QSize(0, 24))
        self.btnCerrarAbout.setObjectName("btnCerrarAbout")
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(30, 10, 61, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.svg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 221, 191))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Acerca de"))
        self.btnCerrarAbout.setText(_translate("dlgAbout", "Cerrar"))
        self.label_2.setText(_translate("dlgAbout", "\n"
"    InmoTeis\n"
"\n"
"    Autor: David Búa Teijeiro\n"
"\n"
"    Versión: 0.0.1\n"
"\n"
"    Copyright © [2024] Inmoteis S.L."))
