# Form implementation generated from reading ui file '.\\templates\\dlgSelectMuni.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgSelectMuni(object):
    def setupUi(self, DlgSelectMuni):
        DlgSelectMuni.setObjectName("DlgSelectMuni")
        DlgSelectMuni.resize(400, 294)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DlgSelectMuni)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=DlgSelectMuni)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cmbMunicipio = QtWidgets.QComboBox(parent=DlgSelectMuni)
        self.cmbMunicipio.setEditable(True)
        self.cmbMunicipio.setObjectName("cmbMunicipio")
        self.verticalLayout.addWidget(self.cmbMunicipio)
        self.btnGenerar = QtWidgets.QPushButton(parent=DlgSelectMuni)
        self.btnGenerar.setObjectName("btnGenerar")
        self.verticalLayout.addWidget(self.btnGenerar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(DlgSelectMuni)
        QtCore.QMetaObject.connectSlotsByName(DlgSelectMuni)

    def retranslateUi(self, DlgSelectMuni):
        _translate = QtCore.QCoreApplication.translate
        DlgSelectMuni.setWindowTitle(_translate("DlgSelectMuni", "Dialog"))
        self.label.setText(_translate("DlgSelectMuni", "Seleccione el municipio"))
        self.btnGenerar.setText(_translate("DlgSelectMuni", "Generar"))
