# Form implementation generated from reading ui file '.\\templates\\dlgSelectMuni.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DlgSelectMuni(object):
    def setupUi(self, DlgSelectMuni):
        DlgSelectMuni.setObjectName("DlgSelectMuni")
        DlgSelectMuni.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=DlgSelectMuni)
        self.label.setGeometry(QtCore.QRect(140, 70, 111, 16))
        self.label.setObjectName("label")
        self.cmbMunicipio = QtWidgets.QComboBox(parent=DlgSelectMuni)
        self.cmbMunicipio.setGeometry(QtCore.QRect(140, 110, 111, 22))
        self.cmbMunicipio.setEditable(True)
        self.cmbMunicipio.setObjectName("cmbMunicipio")
        self.btnGenerar = QtWidgets.QPushButton(parent=DlgSelectMuni)
        self.btnGenerar.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.btnGenerar.setObjectName("btnGenerar")

        self.retranslateUi(DlgSelectMuni)
        QtCore.QMetaObject.connectSlotsByName(DlgSelectMuni)

    def retranslateUi(self, DlgSelectMuni):
        _translate = QtCore.QCoreApplication.translate
        DlgSelectMuni.setWindowTitle(_translate("DlgSelectMuni", "Dialog"))
        self.label.setText(_translate("DlgSelectMuni", "Seleccione el municipio"))
        self.btnGenerar.setText(_translate("DlgSelectMuni", "Generar"))
